/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as DemandIndexRouteImport } from './routes/demand/index'
import { Route as SellerReputationRouteImport } from './routes/seller/reputation'
import { Route as SellerReplayRouteImport } from './routes/seller/replay'
import { Route as SellerMyEventsRouteImport } from './routes/seller/my-events'
import { Route as SellerLiveRouteImport } from './routes/seller/live'
import { Route as SellerHostRouteImport } from './routes/seller/host'
import { Route as SellerCreateEventRouteImport } from './routes/seller/create-event'
import { Route as DemandReplayRouteImport } from './routes/demand/replay'
import { Route as DemandMyEventsRouteImport } from './routes/demand/my-events'
import { Route as DemandLiveRouteImport } from './routes/demand/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandIndexRoute = DemandIndexRouteImport.update({
  id: '/demand/',
  path: '/demand/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerReputationRoute = SellerReputationRouteImport.update({
  id: '/seller/reputation',
  path: '/seller/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerReplayRoute = SellerReplayRouteImport.update({
  id: '/seller/replay',
  path: '/seller/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerMyEventsRoute = SellerMyEventsRouteImport.update({
  id: '/seller/my-events',
  path: '/seller/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerLiveRoute = SellerLiveRouteImport.update({
  id: '/seller/live',
  path: '/seller/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerHostRoute = SellerHostRouteImport.update({
  id: '/seller/host',
  path: '/seller/host',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerCreateEventRoute = SellerCreateEventRouteImport.update({
  id: '/seller/create-event',
  path: '/seller/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandReplayRoute = DemandReplayRouteImport.update({
  id: '/demand/replay',
  path: '/demand/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandMyEventsRoute = DemandMyEventsRouteImport.update({
  id: '/demand/my-events',
  path: '/demand/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandLiveRoute = DemandLiveRouteImport.update({
  id: '/demand/live',
  path: '/demand/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demand/live': typeof DemandLiveRoute
  '/demand/my-events': typeof DemandMyEventsRoute
  '/demand/replay': typeof DemandReplayRoute
  '/seller/create-event': typeof SellerCreateEventRoute
  '/seller/host': typeof SellerHostRoute
  '/seller/live': typeof SellerLiveRoute
  '/seller/my-events': typeof SellerMyEventsRoute
  '/seller/replay': typeof SellerReplayRoute
  '/seller/reputation': typeof SellerReputationRoute
  '/demand/': typeof DemandIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demand/live': typeof DemandLiveRoute
  '/demand/my-events': typeof DemandMyEventsRoute
  '/demand/replay': typeof DemandReplayRoute
  '/seller/create-event': typeof SellerCreateEventRoute
  '/seller/host': typeof SellerHostRoute
  '/seller/live': typeof SellerLiveRoute
  '/seller/my-events': typeof SellerMyEventsRoute
  '/seller/replay': typeof SellerReplayRoute
  '/seller/reputation': typeof SellerReputationRoute
  '/demand': typeof DemandIndexRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demand/live': typeof DemandLiveRoute
  '/demand/my-events': typeof DemandMyEventsRoute
  '/demand/replay': typeof DemandReplayRoute
  '/seller/create-event': typeof SellerCreateEventRoute
  '/seller/host': typeof SellerHostRoute
  '/seller/live': typeof SellerLiveRoute
  '/seller/my-events': typeof SellerMyEventsRoute
  '/seller/replay': typeof SellerReplayRoute
  '/seller/reputation': typeof SellerReputationRoute
  '/demand/': typeof DemandIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demand/live'
    | '/demand/my-events'
    | '/demand/replay'
    | '/seller/create-event'
    | '/seller/host'
    | '/seller/live'
    | '/seller/my-events'
    | '/seller/replay'
    | '/seller/reputation'
    | '/demand/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demand/live'
    | '/demand/my-events'
    | '/demand/replay'
    | '/seller/create-event'
    | '/seller/host'
    | '/seller/live'
    | '/seller/my-events'
    | '/seller/replay'
    | '/seller/reputation'
    | '/demand'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/demand/live'
    | '/demand/my-events'
    | '/demand/replay'
    | '/seller/create-event'
    | '/seller/host'
    | '/seller/live'
    | '/seller/my-events'
    | '/seller/replay'
    | '/seller/reputation'
    | '/demand/'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemandLiveRoute: typeof DemandLiveRoute
  DemandMyEventsRoute: typeof DemandMyEventsRoute
  DemandReplayRoute: typeof DemandReplayRoute
  SellerCreateEventRoute: typeof SellerCreateEventRoute
  SellerHostRoute: typeof SellerHostRoute
  SellerLiveRoute: typeof SellerLiveRoute
  SellerMyEventsRoute: typeof SellerMyEventsRoute
  SellerReplayRoute: typeof SellerReplayRoute
  SellerReputationRoute: typeof SellerReputationRoute
  DemandIndexRoute: typeof DemandIndexRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/': {
      id: '/demand/'
      path: '/demand'
      fullPath: '/demand/'
      preLoaderRoute: typeof DemandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/reputation': {
      id: '/seller/reputation'
      path: '/seller/reputation'
      fullPath: '/seller/reputation'
      preLoaderRoute: typeof SellerReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/replay': {
      id: '/seller/replay'
      path: '/seller/replay'
      fullPath: '/seller/replay'
      preLoaderRoute: typeof SellerReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/my-events': {
      id: '/seller/my-events'
      path: '/seller/my-events'
      fullPath: '/seller/my-events'
      preLoaderRoute: typeof SellerMyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/live': {
      id: '/seller/live'
      path: '/seller/live'
      fullPath: '/seller/live'
      preLoaderRoute: typeof SellerLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/host': {
      id: '/seller/host'
      path: '/seller/host'
      fullPath: '/seller/host'
      preLoaderRoute: typeof SellerHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/create-event': {
      id: '/seller/create-event'
      path: '/seller/create-event'
      fullPath: '/seller/create-event'
      preLoaderRoute: typeof SellerCreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/replay': {
      id: '/demand/replay'
      path: '/demand/replay'
      fullPath: '/demand/replay'
      preLoaderRoute: typeof DemandReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/my-events': {
      id: '/demand/my-events'
      path: '/demand/my-events'
      fullPath: '/demand/my-events'
      preLoaderRoute: typeof DemandMyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/live': {
      id: '/demand/live'
      path: '/demand/live'
      fullPath: '/demand/live'
      preLoaderRoute: typeof DemandLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemandLiveRoute: DemandLiveRoute,
  DemandMyEventsRoute: DemandMyEventsRoute,
  DemandReplayRoute: DemandReplayRoute,
  SellerCreateEventRoute: SellerCreateEventRoute,
  SellerHostRoute: SellerHostRoute,
  SellerLiveRoute: SellerLiveRoute,
  SellerMyEventsRoute: SellerMyEventsRoute,
  SellerReplayRoute: SellerReplayRoute,
  SellerReputationRoute: SellerReputationRoute,
  DemandIndexRoute: DemandIndexRoute,
  SellerIndexRoute: SellerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
